export const points = [
  {
    address: "4735 NORTH BLACKSTONE AVENUE",
    store: "Fresno | Blackstone",
    thumb: "",
    id: "324",
    distance: 0,
    address2: "",
    city: "Fresno",
    state: "CA",
    zip: "93726",
    country: "United States",
    lat: "36.803922",
    lng: "-119.790896",
    phone: "(559) 227-8401",
    fax: "",
    email: "",
    hours: "",
    url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
    intouch_url: "https://meandeds28.intouchposonline.com/",
    offline_url: "",
    specific_offline: ""
  },
  {
    address: "5776 NORTH FIRST STREET",
    store: "Fresno | First",
    thumb: "",
    id: "326",
    distance: 1.7,
    address2: "",
    city: "Fresno",
    state: "CA",
    zip: "93710",
    country: "United States",
    lat: "36.822351",
    lng: "-119.771836",
    phone: "(559) 431-4810",
    fax: "",
    email: "",
    hours: "",
    url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
    intouch_url: "https://meandeds25.intouchposonline.com/",
    offline_url: "",
    specific_offline: ""
  },
  {
    address: "4010 N. Cedar Avenue",
    store: "Victory Grill",
    thumb: "",
    id: "2650",
    distance: 2.2,
    address2: "",
    city: "Fresno",
    state: "CA",
    zip: "93726",
    country: "United States of America",
    lat: "36.789926",
    lng: "-119.756007",
    phone: "(559) 230-0496",
    fax: "",
    email: "",
    hours: "",
    url: "",
    intouch_url: "https://vctry01.intouchposonline.com/",
    offline_url: "",
    specific_offline: ""
  },
  {
  address: "1731 W. BULLARD AVE #101",
  store: "Fresno | Bullard and West | On-Tap",
  thumb: '<img width="45" height="45" src="https://www.meneds.com/wp-content/uploads/2018/12/tap.png" class="wpsl-store-thumb wp-post-image" alt="Fresno | Bullard and West | On-Tap" loading="lazy" />',
  id: "247",
  distance: 2.3,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93711",
  country: "United States",
  lat: "36.822052",
  lng: "-119.825839",
  phone: "(559) 431-7331",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds02.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "7080 N Cedar Avenue",
  store: "Fresno | Cedar and Herndon",
  thumb: "",
  id: "135",
  distance: 3.1,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93720",
  country: "USA",
  lat: "36.838274",
  lng: "-119.754678",
  phone: "(559) 298-7824",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds08.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1736 West Clinton",
  store: "Fresno | Clinton",
  thumb: "",
  id: "273",
  distance: 3.2,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93705",
  country: "United States",
  lat: "36.772252",
  lng: "-119.831926",
  phone: "(559) 485-7952",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds18.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "175 E. Via Del Parque",
  store: "Coney Island",
  thumb: "",
  id: "2652",
  distance: 3.2,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93720",
  country: "United States of America",
  lat: "36.849912",
  lng: "-119.790203",
  phone: "(559) 440-1088",
  fax: "",
  email: "",
  hours: "",
  url: "",
  intouch_url: "https://coney01.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "7025 N West Avenue",
  store: "Fresno | West and Herndon",
  thumb: "",
  id: "340",
  distance: 3.2,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93711",
  country: "United States",
  lat: "36.837753",
  lng: "-119.830005",
  phone: "(559) 436-0563",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds85.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1247 N Wishon",
  store: "Fresno | Tower | On-Tap",
  thumb: '<img width="45" height="45" src="https://www.meneds.com/wp-content/uploads/2018/12/tap.png" class="wpsl-store-thumb wp-post-image" alt="Fresno | Tower | On-Tap" loading="lazy" />',
  id: "338",
  distance: 3.2,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93728",
  country: "United States",
  lat: "36.758455",
  lng: "-119.801339",
  phone: "(559) 442-1247",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds07.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "487 W Shaw Ave",
  store: "Clovis | Peach Ave",
  thumb: "",
  id: "1007",
  distance: 3.9,
  address2: "",
  city: "Clovis",
  state: "CA",
  zip: "93612",
  country: "United States",
  lat: "36.80876",
  lng: "-119.720068",
  phone: "(559) 299-0449",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds10.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "4829 EAST MCKINLEY",
  store: "Fresno | Chestnut",
  thumb: "",
  id: "329",
  distance: 4,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93703",
  country: "United States",
  lat: "36.766508",
  lng: "-119.734984",
  phone: "(559) 251-0397",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds24.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "4177 West Shaw Ave",
  store: "Fresno | Sonora",
  thumb: "",
  id: "335",
  distance: 4.2,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93711",
  country: "United States",
  lat: "36.807528",
  lng: "-119.866649",
  phone: "(559) 276-8341",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds01.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "50 W BULLARD AVE #101",
  store: "Clovis | Minnewawa",
  thumb: "",
  id: "1000",
  distance: 4.6,
  address2: "",
  city: "Clovis",
  state: "CA",
  zip: "93612",
  country: "United States",
  lat: "36.821655",
  lng: "-119.710002",
  phone: "(559) 298-2031",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds11.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1077 North Willow Ave #107",
  store: "Clovis | Willow and Nees",
  thumb: "",
  id: "261",
  distance: 4.7,
  address2: "",
  city: "Clovis",
  state: "CA",
  zip: "93612",
  country: "United States",
  lat: "36.849334",
  lng: "-119.728035",
  phone: "(559) 299-3060",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds75.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "4072 EAST VENTURA AVENUE",
  store: "Fresno | Ventura Ave",
  thumb: "",
  id: "342",
  distance: 5.1,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93702",
  country: "United States",
  lat: "36.735538",
  lng: "-119.756402",
  phone: "(559) 255-1604",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds14.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "10077 N. MAPLE AVE.",
  store: "Fresno | Maple",
  thumb: "",
  id: "331",
  distance: 5.9,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93720",
  country: "United States",
  lat: "36.881709",
  lng: "-119.748621",
  phone: "(559) 434-0166",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds22.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "3150 Fowler Ave #107",
  store: "Clovis | Ashlan and Fowler | On-Tap",
  thumb: '<img width="45" height="45" src="https://www.meneds.com/wp-content/uploads/2018/12/tap.png" class="wpsl-store-thumb wp-post-image" alt="Clovis | Ashlan and Fowler | On-Tap" loading="lazy" />',
  id: "243",
  distance: 5.9,
  address2: "",
  city: "Clovis",
  state: "CA",
  zip: "93611",
  country: "United States",
  lat: "36.795542",
  lng: "-119.684138",
  phone: "(559) 347-9520",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds12.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "5374 W. Spruce Ave",
  store: "Fresno | Polk",
  thumb: "",
  id: "245",
  distance: 6,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93722",
  country: "United States",
  lat: "36.838441",
  lng: "-119.88963",
  phone: "(559) 277-1357",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds03.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "5630 E. Kings Canyon Avenue",
  store: "Fresno | Sunnyside",
  thumb: "",
  id: "133",
  distance: 6.9,
  address2: "",
  city: "Fresno",
  state: "CA",
  zip: "93727",
  country: "USA",
  lat: "36.734485",
  lng: "-119.701217",
  phone: "(559) 255-3011",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds13.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1990 N Fowler Suite 101",
  store: "Clovis | Fowler and Shepherd",
  thumb: "",
  id: "276",
  distance: 7.3,
  address2: "",
  city: "Clovis",
  state: "CA",
  zip: "93619",
  country: "United States",
  lat: "36.865401",
  lng: "-119.684636",
  phone: "(559) 325-0158",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds87.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "765 Temperance Ave #105",
  store: "Clovis | Temperance | On-Tap",
  thumb: '<img width="45" height="45" src="https://www.meneds.com/wp-content/uploads/2018/12/tap.png" class="wpsl-store-thumb wp-post-image" alt="Clovis | Temperance | On-Tap" loading="lazy" />',
  id: "257",
  distance: 7.5,
  address2: "",
  city: "Clovis",
  state: "CA",
  zip: "93611",
  country: "United States",
  lat: "36.845179",
  lng: "-119.664538",
  phone: "559-322-4042",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds79.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "2616 JENSEN AVE",
  store: "Sanger | Jensen Ave",
  thumb: "",
  id: "1024",
  distance: 13.9,
  address2: "",
  city: "Sanger",
  state: "CA",
  zip: "93657",
  country: "United States",
  lat: "36.708232",
  lng: "-119.569372",
  phone: "(559) 875-2528",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds06.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1343 North Ave",
  store: "Sanger | North Ave",
  thumb: "",
  id: "318",
  distance: 15.1,
  address2: "",
  city: "Sanger",
  state: "CA",
  zip: "93657",
  country: "United States",
  lat: "36.691943",
  lng: "-119.55721",
  phone: "(559) 875-8549",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds04.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "15191 West Whitebridge Rd",
  store: "Kerman",
  thumb: "",
  id: "285",
  distance: 15.8,
  address2: "",
  city: "Kerman",
  state: "CA",
  zip: "93630",
  country: "United States",
  lat: "36.734484",
  lng: "-120.062123",
  phone: "(559) 846-6664",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds29.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "3165 South Highland",
  store: "Selma | On-Tap",
  thumb: '<img width="45" height="45" src="https://www.meneds.com/wp-content/uploads/2018/12/tap.png" class="wpsl-store-thumb wp-post-image" alt="Selma | On-Tap" loading="lazy" />',
  id: "287",
  distance: 18.1,
  address2: "",
  city: "Selma",
  state: "CA",
  zip: "93662",
  country: "United States",
  lat: "36.577169",
  lng: "-119.628576",
  phone: "(559) 896-4677",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds27.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "120 Dwyer #B",
  store: "Madera",
  thumb: "",
  id: "281",
  distance: 19,
  address2: "",
  city: "Madera",
  state: "CA",
  zip: "93637",
  country: "United States",
  lat: "36.952138",
  lng: "-120.080621",
  phone: "(559) 675-9613",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds43.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "375 Sierra St",
  store: "Kingsburg",
  thumb: "",
  id: "313",
  distance: 23.4,
  address2: "",
  city: "Kingsburg",
  state: "CA",
  zip: "93631",
  country: "United States",
  lat: "36.51871",
  lng: "-119.564539",
  phone: "(559) 897-0220",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds05.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1085 E MANNING AVE.",
  store: "Reedley",
  thumb: "",
  id: "306",
  distance: 24,
  address2: "",
  city: "Reedley",
  state: "CA",
  zip: "93654",
  country: "United States",
  lat: "36.60381",
  lng: "-119.437747",
  phone: "(559) 638-8113",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds09.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1583 EAST EL MONTE WAY",
  store: "Dinuba",
  thumb: "",
  id: "303",
  distance: 29,
  address2: "",
  city: "Dinuba",
  state: "CA",
  zip: "93618",
  country: "United States",
  lat: "36.546207",
  lng: "-119.378463",
  phone: "(559) 591-6986",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds15.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "2483 North Tenth Ave",
  store: "Hanford | Tenth Ave",
  thumb: "",
  id: "333",
  distance: 32.1,
  address2: "",
  city: "Hanford",
  state: "CA",
  zip: "93230",
  country: "United States",
  lat: "36.356906",
  lng: "-119.636094",
  phone: "(209) 582-6205",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds17.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "711 W. GRANGEVILLE BLVD.",
  store: "Hanford | Grangeville Blvd",
  thumb: "",
  id: "343",
  distance: 32.8,
  address2: "",
  city: "Hanford",
  state: "CA",
  zip: "93230",
  country: "United States",
  lat: "36.342419",
  lng: "-119.655847",
  phone: "(559) 584-9249",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds16.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1290 NORTH LEMOORE",
  store: "Lemoore",
  thumb: "",
  id: "298",
  distance: 33.7,
  address2: "",
  city: "Lemoore",
  state: "CA",
  zip: "93245",
  country: "United States",
  lat: "36.315783",
  lng: "-119.780463",
  phone: "(559) 924-3484",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds21.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "40015 CA-49",
  store: "Oakhurst",
  thumb: "",
  id: "263",
  distance: 37.3,
  address2: "",
  city: "Oakhurst",
  state: "CA",
  zip: "93644",
  country: "United States",
  lat: "37.332524",
  lng: "-119.655983",
  phone: "(559) 642-2929",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds88.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "5105 W. Goshen Ave.",
  store: "Visalia | Goshen Ave",
  thumb: "",
  id: "259",
  distance: 40.4,
  address2: "",
  city: "Visalia",
  state: "CA",
  zip: "93291",
  country: "United States",
  lat: "36.340702",
  lng: "-119.347659",
  phone: "(559) 713-1520",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds76.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1530 N Ben Maddox",
  store: "Visalia | Ben Maddox",
  thumb: "",
  id: "320",
  distance: 42.7,
  address2: "",
  city: "Visalia",
  state: "CA",
  zip: "93291",
  country: "United States",
  lat: "36.343287",
  lng: "-119.278518",
  phone: "(559) 627-1664",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds73.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "4124 S. Mooney Blvd.",
  store: "Visalia | Mooney",
  thumb: "",
  id: "322",
  distance: 44.2,
  address2: "",
  city: "Visalia",
  state: "CA",
  zip: "93277",
  country: "United States",
  lat: "36.292751",
  lng: "-119.312573",
  phone: "(559) 625-5626",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds72.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1217 E. Prosperity",
  store: "Tulare",
  thumb: "",
  id: "301",
  distance: 47.6,
  address2: "",
  city: "Tulare",
  state: "CA",
  zip: "93274",
  country: "United States",
  lat: "36.224575",
  lng: "-119.327451",
  phone: "(559) 684-1381",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds19.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1102 W Visalia Rd",
  store: "Exeter",
  thumb: "",
  id: "255",
  distance: 49.8,
  address2: "",
  city: "Exeter",
  state: "CA",
  zip: "93221",
  country: "United States",
  lat: "36.29696",
  lng: "-119.154374",
  phone: "(559) 592-0252",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds80.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "3524 G ST.",
  store: "Merced",
  thumb: "",
  id: "267",
  distance: 52.1,
  address2: "",
  city: "Merced",
  state: "CA",
  zip: "95340",
  country: "United States",
  lat: "37.330672",
  lng: "-120.468098",
  phone: "(209) 384-2763",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "285 E Elm Ave",
  store: "Coalinga",
  thumb: "",
  id: "348",
  distance: 55.6,
  address2: "",
  city: "Coalinga",
  state: "CA",
  zip: "93210",
  country: "United States",
  lat: "36.141759",
  lng: "-120.358661",
  phone: "(559) 935-1748",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "846 West Pacheco Blvd",
  store: "Los Banos",
  thumb: "",
  id: "283",
  distance: 61.8,
  address2: "",
  city: "Los Banos",
  state: "CA",
  zip: "93635",
  country: "United States",
  lat: "37.057165",
  lng: "-120.864406",
  phone: "(209) 826-1056",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds31.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "1331 West Henderson Ave",
  store: "Porterville",
  thumb: "",
  id: "249",
  distance: 64.9,
  address2: "",
  city: "Porterville",
  state: "CA",
  zip: "93257",
  country: "United States",
  lat: "36.079946",
  lng: "-119.046493",
  phone: "(559) 791-1008",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds98.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "3900 Pelandale #170",
  store: "Modesto",
  thumb: "",
  id: "269",
  distance: 93.6,
  address2: "",
  city: "Modesto",
  state: "CA",
  zip: "95356",
  country: "United States",
  lat: "37.699",
  lng: "-121.067529",
  phone: "(209) 543-0948",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds44.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "4550 Coffee Rd. #L",
  store: "Bakersfield | Coffee Road",
  thumb: "",
  id: "271",
  distance: 104.5,
  address2: "",
  city: "Bakersfield",
  state: "CA",
  zip: "93308",
  country: "United States",
  lat: "35.400813",
  lng: "-119.090378",
  phone: "(661) 588-1811",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds35.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "3300 Buena Vista Rd c3",
  store: "Bakersfield | Buena Vista | On-Tap",
  thumb: '<img width="45" height="45" src="https://www.meneds.com/wp-content/uploads/2018/12/tap.png" class="wpsl-store-thumb wp-post-image" alt="Bakersfield | Buena Vista | On-Tap" loading="lazy" />',
  id: "265",
  distance: 108.8,
  address2: "",
  city: "Bakersfield",
  state: "CA",
  zip: "93311",
  country: "United States",
  lat: "35.323412",
  lng: "-119.128796",
  phone: "(661) 664-7253",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds59.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "4701 Panama Lane",
  store: "Bakersfield | Panama Lane",
  thumb: "",
  id: "279",
  distance: 112,
  address2: "",
  city: "Bakersfield",
  state: "CA",
  zip: "93313",
  country: "United States",
  lat: "35.295559",
  lng: "-119.056682",
  phone: "(661) 836-8290",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds81.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "110 S. Mary Ave # 1",
  store: "Nipomo",
  thumb: "",
  id: "251",
  distance: 128.3,
  address2: "",
  city: "Nipomo",
  state: "CA",
  zip: "93444",
  country: "United States",
  lat: "35.035007",
  lng: "-120.486839",
  phone: "(805) 929-2915",
  fax: "",
  email: "",
  hours: "",
  url: "http://meandeds.intouchposonline.com/start_order/?sid=25&#038;orderType=DELIVERY",
  intouch_url: "https://meandeds90.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "3800 Klose Way",
  store: "Richmond",
  thumb: "",
  id: "2879",
  distance: 161.3,
  address2: "",
  city: "Richmond",
  state: "CA",
  zip: "94806",
  country: "United States",
  lat: "37.983472",
  lng: "-122.327563",
  phone: "(510) 222-2674",
  fax: "",
  email: "",
  hours: "",
  url: "",
  intouch_url: "https://meandeds39.intouchposonline.com/",
  offline_url: "",
  specific_offline: ""
  },
  {
  address: "4115 Paramount Blvd.",
  store: "Lakewood",
  thumb: "",
  id: "2768",
  distance: 224.9,
  address2: "",
  city: "Lakewood",
  state: "CA",
  zip: "90712",
  country: "United States of America",
  lat: "33.833034",
  lng: "-118.162581",
  phone: "(562) 421-8908",
  fax: "",
  email: "",
  hours: "",
  url: "",
  intouch_url: "",
  offline_url: "https://www.zmenu.com/me-n-eds-pizza-parlor-lakewood-online-menu/",
  specific_offline: ""
  }
]