import Head from 'next/head'
import Header from '../Header'
import Footer from '../Footer'


const Layout = ({  children, ...data }) => {
  // console.log('LAYOUT', data.menu)
  return <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app and Tailwindcss" />
        <link rel="icon" href="/cropped-favicon-32x32.png" />
      </Head>
      <Header menu={data.menu} logoUrl={data.logoUrl} franchise={data.franchise} />
        {children}
      <Footer />
    </>
}

export default Layout